# Base image with PyTorch and Python 3.8 (change to the desired version)
FROM pytorch/pytorch:latest

# Install system dependencies for MPI
#RUN apt-get update && apt-get install -y libopenmpi-dev wget && rm -rf /var/lib/apt/lists/*
RUN apt-get --yes -qq update \
 && apt-get --yes -qq upgrade \
 && apt-get --yes -qq install \
                      bzip2 \
                      cmake \
                      cpio \
                      curl \
                      g++ \
                      gcc \
                      gfortran \
                      git \
                      gosu \
                      libblas-dev \
                      liblapack-dev \
                      libopenmpi-dev \
                      openmpi-bin \
                      python3-dev \
                      python3-pip \
                      virtualenv \
                      wget \
                      zlib1g-dev \
                      vim       \
                      htop      \
                      tmux \

 && apt-get --yes -qq clean \
 && rm -rf /var/lib/apt/lists/*



# Set environment variables (optional)
ENV PYTHONUNBUFFERED=1
ENV RAY_REDIS_PASSWORD=5241590000000000

# Create a workspace directory
WORKDIR /workspace

# Copy your local code to the container
COPY ./ /workspace/

COPY ./tmux.conf /.tmux.conf

# Install Ray and additional Python packages
RUN pip install --upgrade pip \
    && pip install ray[tune] \
  pandas \
  geomloss \
  plotly \
  # mpi4py \
  scikit-learn \
  plotnine \
  optuna \
  wandb \
  mlflow \
  umap-learn \
  seaborn \
  webdavclient3  # For webdav connections to the server ...

# Expose Ray's default ports (for head node communication)
EXPOSE 6379 8265 10001

# Default command (modify as needed for your setup)
# CMD ["python", "main.py"]  # Replace with your entry point
CMD ["/bin/bash"]
